### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by robrobinbin** [ZorinOS/zorin-taskbar#1]
Option to only show apps from current workspace

**Comment by jderose9** [comment]
I forked and have merged this feature back in from dash-to-dock.. https://github.com/jderose9/dash-to-panel

**Comment by labsforge** [comment]
Any chance this gets to master? its an essential ux feature..

**Comment by ArtyomZorin** [comment]
This is on the roadmap for the Zorin Taskbar extension in the upcoming release of Zorin OS 16.

**Comment by ArtyomZorin** [comment]
This feature has been added in the latest version of Zorin Taskbar which is due to be included in Zorin OS 16.
