### ISSUE TITLE
How can i install this extension in ubuntu 20.04?

### ISSUE THREAD

**Issue by jonathanbergson** [ZorinOS/zorin-taskbar#11]

**Comment by ShivanshMisra** [comment]
try running 
$ make install ?

**Comment by ArtyomZorin** [comment]
Closing as this isn't a bug report.

**Comment by ShivanshMisra** [comment]
If make install doesn't work try this:
$ sudo add-apt-repository ppa:zorinos/stable
$ sudo apt update && sudo apt install gnome-shell-extension-zorin-taskbar

**Comment by jonathanbergson** [comment]
> If make install doesn't work try this: $ sudo add-apt-repository ppa:zorinos/stable $ sudo apt update && sudo apt install gnome-shell-extension-zorin-taskbar

@ShivanshMisra... this worked, thanks a lot

**Comment by luikluikluik** [comment]
i get the following error:
![image](https://user-images.githubusercontent.com/46636729/187093668-3e6f1f19-17ca-47b8-8d8a-f28aad20ed77.png)
