### ISSUE TITLE
Window preview in taskbar disappears while moving mouse to click on it

### ISSUE THREAD

**Issue by etkaar** [ZorinOS/zorin-taskbar#24]
When hovering over the apps in the taskbar, usually a windows preview opens. But often times the preview disappears while moving the mouse to it to click on it. The reason for this is a small gap between the taskbar and the preview. Is the mouse within this area due to the attempt to click at the preview, the preview will disappear:

![image](https://github.com/user-attachments/assets/66e74149-2acf-4cbd-8943-f35cfa665623)

Here a short screencast. Unfortunately the pointer is not visible due to another bug in the screencast feature:

[Screencast from 2024-09-03 08-45-14.webm](https://github.com/user-attachments/assets/be45519b-d922-4a93-9756-1ceae4dccc13)

A diagonal move, which happens if one has many apps opened, is more likely to trigger this bug.

**Comment by ArtyomZorin** [comment]
It appears that your cursor isn't moving to the window preview before the predefined timeout (previously 100ms).

To help resolve this issue, we've just released an updated version of the Zorin Taskbar that increases the window preview closing timeout to 250ms. To get this update, simply open the Software Updater in Zorin OS 17 and install the latest updates before restarting your computer.

P.S. If you're using the standard built-in screen recorder in Zorin OS 17, you should be able to show the cursor by clicking the "Show Pointer" icon to the right of the red record button.

**Comment by ArtyomZorin** [comment]
> There is a second bug which is related to this issue, see: [home-sweet-gnome/dash-to-panel#2169](https://github.com/home-sweet-gnome/dash-to-panel/issues/2169)

Thanks for letting us know about this potential fix.

We haven't been able to reproduce this issue on any of our computers. However, we've just now released a new software update to the Zorin Taskbar package (version 56.10) in Zorin OS 17 with your patch applied. Please let us know if this resolves the issue.

In addition, could you please let us know the make & model number of your computer, as well as what graphics card model it has (if any)? This would help us to find the original source of this issue.
