### ISSUE TITLE
I can't change keyboard shortcuts to change the keyboard layout language

### ISSUE THREAD

**Issue by Ubuntu-2020** [ZorinOS/zorin-taskbar#7]
**I can't change keyboard shortcuts** to change the **keyboard layout language** in **Zorin OS**.
![ZorinOS-change-lang](https://user-images.githubusercontent.com/65112331/104843175-e2b73a00-58d1-11eb-965f-4c89266f85d7.png)

Currently, the following keyboard shortcuts are used to change the keyboard layout language:
- **Shift**+**Super**+**Space**
- **Super**+**Space**

I believe these are bad keyboard shortcuts :-(
I would suggest these keyboard shortcuts:
- **Shift**+**Alt**
- **Shift**+**Ctrl**

I apologize that is not quite on the topic.

**Comment by ArtyomZorin** [comment]
Closing as this issue is not related to the Zorin Taskbar package.

We're preparing a new keyboard shortcut settings dialog for Zorin OS 16, so stay tuned to our Blog for this upcoming release: https://blog.zorin.com/
