### ISSUE TITLE
Feature request: Add the extension to the browser

### ISSUE THREAD

**Issue by Ubuntu-2020** [ZorinOS/zorin-taskbar#8]
Add the **[Kiwix](https://en.wikipedia.org/wiki/Kiwix)** **[extension](https://addons.mozilla.org/fr/firefox/addon/kiwix-offline/)** to the FireFox browser in **Zorin OS Education**.
I think that for the **Educational** version this extension will be very suitable and it **weighs very little**!

**Comment by ArtyomZorin** [comment]
Closing as this issue is not related to the Zorin Taskbar package.

Please do not post Zorin OS feature suggestions not related to Zorin Taskbar here. I would recommend you to send these suggestions using our contact form here: https://zorinos.com/about/#contact
