### ISSUE TITLE
How to re-install it on Zorin16

### ISSUE THREAD

**Issue by Kazvko** [ZorinOS/zorin-taskbar#9]
I've accidentally upgraded this extension on gnome extensions website, and turns out it broke my topbar for good. Since here is the source of the extension, could you help me on this?

**Comment by Bobj2018** [comment]
I think I have the same issue

**Comment by ArtyomZorin** [comment]
You can re-install the Zorin Taskbar extension in Zorin OS 16 opening the Terminal (Ctrl+Alt+T) and entering this command:
`sudo apt reinstall gnome-shell-extension-zorin-taskbar`

The version that's on the Gnome Extensions website was not uploaded by us and is not official, so we would recommend you not to use it.

Closing as this isn't a bug report.
